---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен имееть возможность ввести цену от 0 до 11190
  - Пользователь должен имееть возможность вводить отрицательное число в строку поиска товара по цене
  - В наличие имеется определенное количество каждого товара, поэтому пользователь должен имееть возможность выбрать определенное количество каждого товара
  - Пользователь должен иметь возможность выбрать несколько товаров и добавить их в корзину 
  - Пользователь должен иметь возможность изменить язык интерфейса
  - Даже после добавления товара в корзину, пользователь должен иметь возможность вернуться на страницу с товаром, чтобы продолжить выбирать товар и может добавить его в корзину
  - Пользователь должен иметь возможность переходить на другую страницу с товаром без перезагрузки сайта
  - После нажатия кнопки "оформить заказ" должны отображаться названия товаров, количество каждого товара, цена каждого товара и общая сумма
  - После нажатия кнопки "оформить заказ" должна высвечиваться надпись "Заказ успешно оформлен"
  - После нажатия на кнопку "очистить корзину" товары в корзине должны очищаться
  - После нажатия на кнопку "продолжить покупки" пользователь должен имееть возмозность дальше выбирать товары и добавлять их в корзину
  - Когда пользователь выбирает категорию в наличии и ставит галочку, должен высвечивать весь товар который в наличии и наоборот
  - Должна быть возможность перехода на официальный сайт Hexler
  - Все элементы должны быстро прогружаться и не должно быть никаких ошибок
  - После оформления заказа пользователь должен иметь возможность закрыть всплывающее окно и вернуться в корзину
